#!/bin/bash

trap finish EXIT

MUG_VR_DIR="$(dirname "$(readlink -f "$0")")"
SCRIPTS_DIR="$MUG_VR_DIR"/bootstrap_scripts
TEMP="$SCRIPTS_DIR"/tmp
DEFAULT_FOLDERS=""
KVM_USER_HOME=/home/kvm_user

finish()
{
    set +x
    rm -Rf "$TEMP"
}


usage()
{
    cat << EOF
Usage:
    $0 -c <configure script dir> -m <module install dir>
EOF

    exit "$1"
}

# $*: list of colon-separated folders with scripts to be merged to run in
#     the virtualized system bootstrap
configure_scripts()
{
    rm -Rf "$TEMP"
    mkdir "$TEMP"

    if (( "${#F[@]}" < 1 ))
    then
        return 1
    fi

    local IFS=':'
    read -ra F <<< "$@"
    for i in "${F[@]}"
    do
        cp "$SCRIPTS_DIR/$i"/* "$TEMP"
    done

    SCRIPT="--script-dir $TEMP"
}

set -x

parse_arguments()
{
    while getopts ":c:m:h" opt
    do
        case $opt in
            c ) CONFIG_DIR=$OPTARG;;
            m ) MDIR=$OPTARG;;
            h ) usage 0;;
            * ) usage 1;;
        esac
    done

    if [[ -n $MDIR ]]
    then
        MDIR="--mdir=$MDIR"
    fi
}

main()
{
    configure_scripts "${DEFAULT_FOLDERS}:${CONFIG_DIR}"

    VIRTME_ARGS="--kdir=$KERNEL_DIR --cwd=. --home=${KVM_USER_HOME} --graphics $SCRIPT $MDIR"
    QEMU_ARGS="-vga virtio -smp 2 -m 2G -show-cursor"
    export SDL_VIDEO_X11_DGAMOUSE=0
    eval "virtme-run $VIRTME_ARGS --qemu-opts $QEMU_ARGS"

    rm -Rf "$TEMP"
}

parse_arguments "$@"
main
